
# === Backtest Config (edit me) ===
# Secrets: put MONGODB_URI in `.env` (see .env.example).

# Optional CSV fallback (if set, use CSV instead of Mongo):
# csv_path: "/path/to/klines.csv"

mongo_db: "market_info"
mongo_coll: "BNBUSDT_1h_Binance"

symbol: "BNBUSDT"
interval: "1h"

# ISO8601 or epoch ms
start: "2025-02-01T00:00:00Z"
end:   "2025-09-01T00:00:00Z"

ckpt_path: "model/checkpoints/ohlcv/20250830-122134_best_forBTC.pt"
device: null

fee_bps: 1.0
slippage_bps: 0.0
initial_capital: 10000.0
threshold: 0.0
